# Configurazione Android Studio per Node.js
idea.required.plugins.id=org.jetbrains.android
PATH=/Users/marcorispoli/.nvm/versions/node/v21.7.1/bin:/usr/local/bin:/usr/bin:/bin
NODE_PATH=/Users/marcorispoli/.nvm/versions/node/v21.7.1/bin
NODE_HOME=/Users/marcorispoli/.nvm/versions/node/v21.7.1
